# Generated by Django 5.2.5 on 2025-08-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('motivo', models.TextField(verbose_name='Motivo de la carta')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
        ),
    ]
