# Generated by Django 5.2.5 on 2025-08-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_trabajador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='edad',
            field=models.CharField(max_length=100, verbose_name='edad'),
        ),
    ]
