# Generated by Django 5.2.5 on 2025-08-18 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_trabajador_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.cliente', verbose_name='Cliente')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.trabajador', verbose_name='Trabajador')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.estado', verbose_name='Estado')),
            ],
        ),
    ]
