# Generated by Django 5.2.5 on 2025-08-19 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_estado_carta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='fecha',
        ),
    ]
