# Generated by Django 5.2.5 on 2025-08-19 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_remove_carta_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTrabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='trabajador',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.estadotrabajador', verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
