# Generated by Django 5.2.5 on 2025-08-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_estadotrabajador_trabajador_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajador',
            old_name='estado',
            new_name='estadoTra',
        ),
    ]
